export const ERP_TEMPLATE = {
  phases: [
    {
      phaseNumber: 1,
      phaseName: "Pre-Implementation Planning",
      order: 1,
      tasks: [
        { section: "Kick-off Meeting", taskType: "activity",    taskName: "Introduce project teams from both sides", order: 1 },
        { section: "Kick-off Meeting", taskType: "activity",    taskName: "Review and confirm project scope", order: 2 },
        { section: "Kick-off Meeting", taskType: "activity",    taskName: "Define communication channels and meeting schedules", order: 3 },
        { section: "Kick-off Meeting", taskType: "activity",    taskName: "Distribute roles and responsibilities", order: 4 },
        { section: "Kick-off Meeting", taskType: "activity",    taskName: "Obtain formal project kick-off sign-off", order: 5 },
        { section: "Kick-off Meeting", taskType: "deliverable", taskName: "Kick-off Meeting Minutes", order: 6 },
        { section: "Kick-off Meeting", taskType: "deliverable", taskName: "Project Charter (signed)", order: 7 },
        { section: "Kick-off Meeting", taskType: "deliverable", taskName: "Contact List of All Stakeholders", order: 8 },

        { section: "Requirement Gathering", taskType: "activity",    taskName: "Schedule department-wise interviews (Finance, HR, Sales, Purchase, Inventory)", order: 9 },
        { section: "Requirement Gathering", taskType: "activity",    taskName: "Study existing workflows and reports", order: 10 },
        { section: "Requirement Gathering", taskType: "activity",    taskName: "Identify pain points in the current system", order: 11 },
        { section: "Requirement Gathering", taskType: "activity",    taskName: "Document all requirements clearly", order: 12 },
        { section: "Requirement Gathering", taskType: "deliverable", taskName: "Business Requirement Document (BRD)", order: 13 },
        { section: "Requirement Gathering", taskType: "deliverable", taskName: "AS-IS Process Document", order: 14 },
        { section: "Requirement Gathering", taskType: "deliverable", taskName: "Stakeholder Interview Notes", order: 15 },

        { section: "Gap Analysis", taskType: "activity",    taskName: "Map each requirement to ERP modules", order: 16 },
        { section: "Gap Analysis", taskType: "activity",    taskName: "Identify features available out-of-the-box", order: 17 },
        { section: "Gap Analysis", taskType: "activity",    taskName: "List items needing customization or development", order: 18 },
        { section: "Gap Analysis", taskType: "activity",    taskName: "Prioritize customizations (Must-Have / Nice-to-Have)", order: 19 },
        { section: "Gap Analysis", taskType: "deliverable", taskName: "Gap Analysis Report", order: 20 },
        { section: "Gap Analysis", taskType: "deliverable", taskName: "Customization Requirements List", order: 21 },
      ],
    },
    {
      phaseNumber: 2,
      phaseName: "Project Planning",
      order: 2,
      tasks: [
        { section: "Project Plan", taskType: "milestone",   taskName: "Requirement Gathering Complete", order: 1 },
        { section: "Project Plan", taskType: "milestone",   taskName: "Gap Analysis Sign-off", order: 2 },
        { section: "Project Plan", taskType: "milestone",   taskName: "Configuration Complete", order: 3 },
        { section: "Project Plan", taskType: "milestone",   taskName: "UAT Sign-off", order: 4 },
        { section: "Project Plan", taskType: "milestone",   taskName: "Go-Live", order: 5 },
        { section: "Project Plan", taskType: "milestone",   taskName: "Post Go-Live Support End", order: 6 },
        { section: "Project Plan", taskType: "deliverable", taskName: "Project Plan / Gantt Chart", order: 7 },
        { section: "Project Plan", taskType: "deliverable", taskName: "Work Breakdown Structure (WBS)", order: 8 },
        { section: "Project Plan", taskType: "deliverable", taskName: "Resource Allocation Plan", order: 9 },

        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "Server provisioned", order: 10 },
        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "OS installed and updated", order: 11 },
        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "Database server configured", order: 12 },
        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "DEV environment live", order: 13 },
        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "QA environment live", order: 14 },
        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "PROD environment live", order: 15 },
        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "Backup configured", order: 16 },
        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "SSL certificate installed", order: 17 },
        { section: "Infrastructure Setup", taskType: "checklist",  taskName: "Firewall rules configured", order: 18 },
        { section: "Infrastructure Setup", taskType: "deliverable", taskName: "Infrastructure Setup Document", order: 19 },
        { section: "Infrastructure Setup", taskType: "deliverable", taskName: "Environment Details Sheet", order: 20 },
      ],
    },
    {
      phaseNumber: 3,
      phaseName: "System Configuration & Customization",
      order: 3,
      tasks: [
        { section: "Base Configuration", taskType: "activity",    taskName: "Company profile setup (name, logo, address, currency, fiscal year)", order: 1 },
        { section: "Base Configuration", taskType: "activity",    taskName: "Tax configuration (GST, TDS, TCS as applicable)", order: 2 },
        { section: "Base Configuration", taskType: "activity",    taskName: "Organizational structure (branches, departments, cost centers)", order: 3 },
        { section: "Base Configuration", taskType: "activity",    taskName: "User roles and permissions setup", order: 4 },
        { section: "Base Configuration", taskType: "activity",    taskName: "Workflow and approval hierarchy configuration", order: 5 },
        { section: "Base Configuration", taskType: "activity",    taskName: "Email and notification settings", order: 6 },
        { section: "Base Configuration", taskType: "deliverable", taskName: "Configuration Document (settings with screenshots)", order: 7 },
        { section: "Base Configuration", taskType: "deliverable", taskName: "User Role Matrix", order: 8 },

        { section: "Master Data Setup", taskType: "checklist",  taskName: "Chart of Accounts (Finance Team)", order: 9 },
        { section: "Master Data Setup", taskType: "checklist",  taskName: "Customer Master (Sales Team)", order: 10 },
        { section: "Master Data Setup", taskType: "checklist",  taskName: "Vendor / Supplier Master (Purchase Team)", order: 11 },
        { section: "Master Data Setup", taskType: "checklist",  taskName: "Item / Product Master (Inventory Team)", order: 12 },
        { section: "Master Data Setup", taskType: "checklist",  taskName: "Employee Master (HR Team)", order: 13 },
        { section: "Master Data Setup", taskType: "checklist",  taskName: "Warehouse / Location Master (Warehouse Team)", order: 14 },
        { section: "Master Data Setup", taskType: "checklist",  taskName: "Price List (Sales / Finance)", order: 15 },
        { section: "Master Data Setup", taskType: "checklist",  taskName: "Tax Codes (Finance Team)", order: 16 },
        { section: "Master Data Setup", taskType: "deliverable", taskName: "Master Data Templates (Excel)", order: 17 },
        { section: "Master Data Setup", taskType: "deliverable", taskName: "Master Data Upload Confirmation Sheet", order: 18 },

        { section: "Customization & Development", taskType: "activity",    taskName: "Develop custom modules as per gap analysis", order: 19 },
        { section: "Customization & Development", taskType: "activity",    taskName: "Create custom reports and dashboards", order: 20 },
        { section: "Customization & Development", taskType: "activity",    taskName: "Build third-party integrations (bank, payroll, e-commerce)", order: 21 },
        { section: "Customization & Development", taskType: "activity",    taskName: "Develop custom approval workflows", order: 22 },
        { section: "Customization & Development", taskType: "activity",    taskName: "Code review and unit testing", order: 23 },
        { section: "Customization & Development", taskType: "deliverable", taskName: "Technical Specification Document", order: 24 },
        { section: "Customization & Development", taskType: "deliverable", taskName: "Custom Module / Integration Document", order: 25 },
        { section: "Customization & Development", taskType: "deliverable", taskName: "Code Review Sign-off", order: 26 },

        { section: "Data Migration", taskType: "activity",    taskName: "Extract — Export data from legacy system", order: 27 },
        { section: "Data Migration", taskType: "activity",    taskName: "Clean — Remove duplicates, fix errors, standardize format", order: 28 },
        { section: "Data Migration", taskType: "activity",    taskName: "Map — Map old fields to new ERP fields", order: 29 },
        { section: "Data Migration", taskType: "activity",    taskName: "Transform — Convert data to ERP-compatible format", order: 30 },
        { section: "Data Migration", taskType: "activity",    taskName: "Load (Test) — Do a test migration in DEV/QA environment", order: 31 },
        { section: "Data Migration", taskType: "activity",    taskName: "Validate — Verify data accuracy and completeness", order: 32 },
        { section: "Data Migration", taskType: "activity",    taskName: "Load (Final) — Final migration to PROD during Go-Live cutover", order: 33 },
        { section: "Data Migration", taskType: "checklist",  taskName: "Customer Data migrated", order: 34 },
        { section: "Data Migration", taskType: "checklist",  taskName: "Vendor Data migrated", order: 35 },
        { section: "Data Migration", taskType: "checklist",  taskName: "Item / Product Data migrated", order: 36 },
        { section: "Data Migration", taskType: "checklist",  taskName: "Opening Balances entered", order: 37 },
        { section: "Data Migration", taskType: "checklist",  taskName: "Employee Data migrated", order: 38 },
        { section: "Data Migration", taskType: "checklist",  taskName: "Historical Transactions migrated", order: 39 },
        { section: "Data Migration", taskType: "deliverable", taskName: "Data Migration Plan", order: 40 },
        { section: "Data Migration", taskType: "deliverable", taskName: "Data Mapping Sheet", order: 41 },
        { section: "Data Migration", taskType: "deliverable", taskName: "Data Migration Sign-off", order: 42 },
      ],
    },
    {
      phaseNumber: 4,
      phaseName: "Testing",
      order: 4,
      tasks: [
        { section: "Unit Testing", taskType: "activity", taskName: "Developer team performs unit testing for all configured features", order: 1 },
        { section: "Unit Testing", taskType: "activity", taskName: "Cover all customizations in DEV environment", order: 2 },
        { section: "Unit Testing", taskType: "deliverable", taskName: "Unit Test Cases Document", order: 3 },

        { section: "System Integration Testing (SIT)", taskType: "activity",    taskName: "Test: Sales order → Inventory deduction → Invoice generation", order: 4 },
        { section: "System Integration Testing (SIT)", taskType: "activity",    taskName: "Test: Purchase order → Goods receipt → Vendor payment", order: 5 },
        { section: "System Integration Testing (SIT)", taskType: "activity",    taskName: "Test: Employee payroll → Finance posting", order: 6 },
        { section: "System Integration Testing (SIT)", taskType: "activity",    taskName: "Test: Production order → Raw material consumption → Finished goods", order: 7 },
        { section: "System Integration Testing (SIT)", taskType: "deliverable", taskName: "SIT Test Cases Document", order: 8 },
        { section: "System Integration Testing (SIT)", taskType: "deliverable", taskName: "SIT Defect Log", order: 9 },
        { section: "System Integration Testing (SIT)", taskType: "deliverable", taskName: "SIT Sign-off", order: 10 },

        { section: "User Acceptance Testing (UAT)", taskType: "activity",    taskName: "Share UAT Test Cases with client", order: 11 },
        { section: "User Acceptance Testing (UAT)", taskType: "activity",    taskName: "Client users execute test scenarios", order: 12 },
        { section: "User Acceptance Testing (UAT)", taskType: "activity",    taskName: "Record pass/fail status for each test case", order: 13 },
        { section: "User Acceptance Testing (UAT)", taskType: "activity",    taskName: "Log defects with screenshots and descriptions", order: 14 },
        { section: "User Acceptance Testing (UAT)", taskType: "activity",    taskName: "Development team fixes defects", order: 15 },
        { section: "User Acceptance Testing (UAT)", taskType: "activity",    taskName: "Re-test failed cases", order: 16 },
        { section: "User Acceptance Testing (UAT)", taskType: "activity",    taskName: "Obtain UAT Sign-off from client", order: 17 },
        { section: "User Acceptance Testing (UAT)", taskType: "deliverable", taskName: "UAT Test Cases Document", order: 18 },
        { section: "User Acceptance Testing (UAT)", taskType: "deliverable", taskName: "UAT Defect Log", order: 19 },
        { section: "User Acceptance Testing (UAT)", taskType: "deliverable", taskName: "UAT Sign-off (Client Signature Required)", order: 20 },
      ],
    },
    {
      phaseNumber: 5,
      phaseName: "Training",
      order: 5,
      tasks: [
        { section: "Training Sessions", taskType: "activity",    taskName: "Session 1: Finance module — Accounts Team (4 Hours)", order: 1 },
        { section: "Training Sessions", taskType: "activity",    taskName: "Session 2: HR & Payroll — HR Team (4 Hours)", order: 2 },
        { section: "Training Sessions", taskType: "activity",    taskName: "Session 3: Sales & CRM — Sales Team (3 Hours)", order: 3 },
        { section: "Training Sessions", taskType: "activity",    taskName: "Session 4: Purchase — Purchase Team (3 Hours)", order: 4 },
        { section: "Training Sessions", taskType: "activity",    taskName: "Session 5: Inventory — Warehouse Team (3 Hours)", order: 5 },
        { section: "Training Sessions", taskType: "activity",    taskName: "Session 6: Admin & Reports — IT / Management (2 Hours)", order: 6 },
        { section: "Training Deliverables", taskType: "deliverable", taskName: "User Manual (Module-wise, PDF format)", order: 7 },
        { section: "Training Deliverables", taskType: "deliverable", taskName: "Quick Reference Guide (QRG) — 1-2 page cheat sheet per module", order: 8 },
        { section: "Training Deliverables", taskType: "deliverable", taskName: "Training Videos (recorded sessions)", order: 9 },
        { section: "Training Deliverables", taskType: "deliverable", taskName: "Training Attendance Sheet (with signatures)", order: 10 },
      ],
    },
    {
      phaseNumber: 6,
      phaseName: "Go-Live",
      order: 6,
      tasks: [
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "UAT Sign-off received (Client POC)", order: 1 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "All critical defects resolved (Dev Lead)", order: 2 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "Final data migration completed (Technical Lead)", order: 3 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "Data validation done (Functional Consultant)", order: 4 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "Production environment ready (Infrastructure Team)", order: 5 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "All users created with correct roles (System Admin)", order: 6 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "Email and notifications configured (System Admin)", order: 7 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "Backup configured and tested (Infrastructure Team)", order: 8 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "Training completed for all users (Trainer)", order: 9 },
        { section: "Go-Live Checklist", taskType: "checklist", taskName: "Go/No-Go approval received (Project Manager + Client)", order: 10 },

        { section: "Go/No-Go Decision", taskType: "checklist", taskName: "All critical UAT cases passed", order: 11 },
        { section: "Go/No-Go Decision", taskType: "checklist", taskName: "Data migration validated", order: 12 },
        { section: "Go/No-Go Decision", taskType: "checklist", taskName: "Infrastructure ready", order: 13 },
        { section: "Go/No-Go Decision", taskType: "checklist", taskName: "Training completed", order: 14 },
        { section: "Go/No-Go Decision", taskType: "checklist", taskName: "Client approval received", order: 15 },

        { section: "Cutover Plan", taskType: "activity", taskName: "Freeze old system (stop data entry) — T-Day 06:00 PM", order: 16 },
        { section: "Cutover Plan", taskType: "activity", taskName: "Final data export from legacy system — T-Day 07:00 PM", order: 17 },
        { section: "Cutover Plan", taskType: "activity", taskName: "Final data migration to PROD — T-Day 09:00 PM", order: 18 },
        { section: "Cutover Plan", taskType: "activity", taskName: "Data validation in PROD — T-Day 11:00 PM", order: 19 },
        { section: "Cutover Plan", taskType: "activity", taskName: "Open ERP for users — Go-Live Day 09:00 AM", order: 20 },
        { section: "Cutover Plan", taskType: "activity", taskName: "Monitor live transactions — Go-Live Day onwards", order: 21 },
      ],
    },
    {
      phaseNumber: 7,
      phaseName: "Post Go-Live Support",
      order: 7,
      tasks: [
        { section: "Hypercare Support", taskType: "checklist", taskName: "Critical (System Down): Response 1 Hour / Resolution 4 Hours — SLA Agreed", order: 1 },
        { section: "Hypercare Support", taskType: "checklist", taskName: "High (Core function broken): Response 2 Hours / Resolution 8 Hours — SLA Agreed", order: 2 },
        { section: "Hypercare Support", taskType: "checklist", taskName: "Medium (Partial impact): Response 4 Hours / Resolution 24 Hours — SLA Agreed", order: 3 },
        { section: "Hypercare Support", taskType: "checklist", taskName: "Low (Minor/cosmetic): Response 8 Hours / Resolution 72 Hours — SLA Agreed", order: 4 },

        { section: "Support Activities", taskType: "activity", taskName: "Daily system health monitoring", order: 5 },
        { section: "Support Activities", taskType: "activity", taskName: "Bug fixes and patch releases", order: 6 },
        { section: "Support Activities", taskType: "activity", taskName: "Weekly review meetings with client", order: 7 },
        { section: "Support Activities", taskType: "activity", taskName: "User query resolution", order: 8 },
        { section: "Support Activities", taskType: "activity", taskName: "Performance tuning", order: 9 },

        { section: "Project Closure", taskType: "checklist", taskName: "Final documentation handover", order: 10 },
        { section: "Project Closure", taskType: "checklist", taskName: "Admin credentials handover", order: 11 },
        { section: "Project Closure", taskType: "checklist", taskName: "Knowledge transfer to client IT team", order: 12 },
        { section: "Project Closure", taskType: "checklist", taskName: "Sign AMC / SLA Support Agreement", order: 13 },
        { section: "Project Closure", taskType: "checklist", taskName: "Project Closure Report sign-off", order: 14 },
      ],
    },
  ],

  documents: [
    { docNumber: 1,  category: "Planning",                 title: "Project Charter",                         preparedBy: "Project Manager"      },
    { docNumber: 2,  category: "Planning",                 title: "Scope of Work (SOW)",                     preparedBy: "Project Manager"      },
    { docNumber: 3,  category: "Planning",                 title: "Project Plan / Gantt Chart",              preparedBy: "Project Manager"      },
    { docNumber: 4,  category: "Planning",                 title: "Resource Allocation Plan",                preparedBy: "Project Manager"      },
    { docNumber: 5,  category: "Planning",                 title: "Risk Register",                           preparedBy: "Project Manager"      },
    { docNumber: 6,  category: "Planning",                 title: "Communication Plan",                      preparedBy: "Project Manager"      },
    { docNumber: 7,  category: "Requirement & Analysis",   title: "Business Requirement Document (BRD)",     preparedBy: "Functional Consultant"},
    { docNumber: 8,  category: "Requirement & Analysis",   title: "Functional Requirement Specification (FRS)", preparedBy: "Functional Consultant"},
    { docNumber: 9,  category: "Requirement & Analysis",   title: "AS-IS Process Document",                  preparedBy: "Functional Consultant"},
    { docNumber: 10, category: "Requirement & Analysis",   title: "TO-BE Process Document",                  preparedBy: "Functional Consultant"},
    { docNumber: 11, category: "Requirement & Analysis",   title: "Gap Analysis Report",                     preparedBy: "Functional Consultant"},
    { docNumber: 12, category: "Design & Technical",       title: "System Design Document (SDD)",            preparedBy: "Technical Lead"       },
    { docNumber: 13, category: "Design & Technical",       title: "Database Design / ER Diagram",            preparedBy: "Technical Lead"       },
    { docNumber: 14, category: "Design & Technical",       title: "Integration Design Document",             preparedBy: "Technical Lead"       },
    { docNumber: 15, category: "Design & Technical",       title: "Data Migration Plan & Mapping Sheet",     preparedBy: "Technical Lead"       },
    { docNumber: 16, category: "Design & Technical",       title: "Customization / Development Specification",preparedBy: "Developer"           },
    { docNumber: 17, category: "Design & Technical",       title: "Configuration Document",                  preparedBy: "Functional Consultant"},
    { docNumber: 18, category: "Testing",                  title: "Test Plan",                               preparedBy: "QA Lead"              },
    { docNumber: 19, category: "Testing",                  title: "Unit Test Cases",                         preparedBy: "Developer"            },
    { docNumber: 20, category: "Testing",                  title: "SIT Test Cases",                          preparedBy: "QA Lead"              },
    { docNumber: 21, category: "Testing",                  title: "UAT Test Cases",                          preparedBy: "Functional Consultant"},
    { docNumber: 22, category: "Testing",                  title: "Defect / Bug Tracker",                    preparedBy: "QA Lead"              },
    { docNumber: 23, category: "Testing",                  title: "UAT Sign-off Document",                   preparedBy: "Client POC"           },
    { docNumber: 24, category: "Training",                 title: "Training Plan",                           preparedBy: "Functional Consultant"},
    { docNumber: 25, category: "Training",                 title: "User Manual (Module-wise)",               preparedBy: "Functional Consultant"},
    { docNumber: 26, category: "Training",                 title: "Quick Reference Guide (QRG)",             preparedBy: "Functional Consultant"},
    { docNumber: 27, category: "Training",                 title: "Training Attendance Sheet",               preparedBy: "Project Manager"      },
    { docNumber: 28, category: "Go-Live",                  title: "Go-Live Checklist",                       preparedBy: "Project Manager"      },
    { docNumber: 29, category: "Go-Live",                  title: "Cutover Plan",                            preparedBy: "Technical Lead"       },
    { docNumber: 30, category: "Go-Live",                  title: "Go/No-Go Approval Sign-off",              preparedBy: "Project Manager"      },
    { docNumber: 31, category: "Go-Live",                  title: "Data Migration Sign-off",                 preparedBy: "Technical Lead + Client"},
    { docNumber: 32, category: "Post Go-Live & Closure",   title: "Hypercare Support Log",                   preparedBy: "Support Team"         },
    { docNumber: 33, category: "Post Go-Live & Closure",   title: "Known Issues & Resolution Tracker",       preparedBy: "Support Team"         },
    { docNumber: 34, category: "Post Go-Live & Closure",   title: "SLA / AMC Support Agreement",            preparedBy: "Project Manager"      },
    { docNumber: 35, category: "Post Go-Live & Closure",   title: "Project Closure Report",                  preparedBy: "Project Manager"      },
    { docNumber: 36, category: "Post Go-Live & Closure",   title: "Handover Document",                       preparedBy: "Technical Lead"       },
  ],

  risks: [
    { riskNumber: 1, description: "Scope creep due to uncontrolled change requests",  probability: "High",   impact: "High",   mitigation: "Formal CR process with sign-off" },
    { riskNumber: 2, description: "Data quality issues during migration",              probability: "High",   impact: "High",   mitigation: "Early data audit and cleansing" },
    { riskNumber: 3, description: "Key client users unavailable for UAT",             probability: "Medium", impact: "High",   mitigation: "Schedule UAT well in advance" },
    { riskNumber: 4, description: "Infrastructure delays",                             probability: "Medium", impact: "High",   mitigation: "Finalize infrastructure in Phase 1" },
    { riskNumber: 5, description: "Resistance to change by end users",                probability: "Medium", impact: "Medium", mitigation: "Change management and training" },
    { riskNumber: 6, description: "Integration failure with third-party systems",      probability: "Low",    impact: "High",   mitigation: "Detailed integration testing" },
    { riskNumber: 7, description: "Go-Live date slip",                                 probability: "Medium", impact: "High",   mitigation: "Buffer weeks in project plan" },
  ],
}
