import { NextRequest, NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import nodemailer from "nodemailer"

const transporter = nodemailer.createTransport({
  host:   process.env.SMTP_HOST,
  port:   Number(process.env.SMTP_PORT ?? 587),
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
})

function buildHtml(type: string, data: any): string {
  const date = data.date ?? data.period ?? new Date().toDateString()
  const title = `${type.charAt(0).toUpperCase() + type.slice(1)} Progress Report — ${date}`

  const summaryRows = Object.entries(data.summary ?? {})
    .map(([k, v]) => `<tr><td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;color:#6b7280;font-size:13px">${k.replace(/([A-Z])/g, " $1").trim()}</td><td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;font-weight:600;font-size:13px">${v}</td></tr>`)
    .join("")

  return `
    <!DOCTYPE html><html><body style="font-family:-apple-system,sans-serif;background:#f8fafc;padding:32px">
    <div style="max-width:640px;margin:0 auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)">
      <div style="background:#2563eb;padding:24px 32px">
        <h1 style="color:white;margin:0;font-size:20px">${title}</h1>
        <p style="color:#bfdbfe;margin:4px 0 0;font-size:13px">Generated by Agile Progress Tracker</p>
      </div>
      <div style="padding:24px 32px">
        <h2 style="color:#1e293b;font-size:15px;margin-bottom:12px">Summary</h2>
        <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden">
          ${summaryRows}
        </table>
        <p style="color:#94a3b8;font-size:12px;margin-top:24px">
          This report was sent by ${process.env.SMTP_USER} via Agile Progress Tracker.<br>
          Generated at ${new Date().toLocaleString()}
        </p>
      </div>
    </div>
    </body></html>
  `
}

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { type, data, to } = await req.json()
  const recipients = to ?? process.env.MANAGER_EMAIL ?? ""

  if (!recipients) return NextResponse.json({ error: "No recipient configured" }, { status: 400 })

  await transporter.sendMail({
    from:    `"Agile Tracker" <${process.env.SMTP_USER}>`,
    to:      recipients,
    subject: `[Agile Tracker] ${type.charAt(0).toUpperCase() + type.slice(1)} Progress Report`,
    html:    buildHtml(type, data),
  })

  return NextResponse.json({ success: true })
}
